#                                 __                 __
#    __  ______  ____ ___  ____ _/ /____  ____  ____/ /
#   / / / / __ \/ __ `__ \/ __ `/ __/ _ \/ __ \/ __  /
#  / /_/ / /_/ / / / / / / /_/ / /_/  __/ /_/ / /_/ /
#  \__, /\____/_/ /_/ /_/\__,_/\__/\___/\____/\__,_/
# /____                     matthewdavis.io, holla!
#
SHELL := /bin/bash

install:
install-sdk:

	curl -s "https://get.sdkman.io" | bash

	source "$(HOME)/.sdkman/bin/sdkman-init.sh"

	sdk version
